### ISSUE TITLE
Native support of Infracost diff

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#1017]
There is no clean way to achieve infracost diff with Digger

Currently infracost integration is [supported](https://docs.digger.dev/howto/using-infracost) via custom commands; but that only gives breakdown

For diff, infracost needs to be called 2 times
- checkout main, then generate base json
- checkout branch, then generate diff json

If there was only 1 project, it could be achieved by additional checkout steps in the workflow file (as per [infracost action docs](https://github.com/infracost/actions?tab=readme-ov-file#quick-start)). But with more than 1 project this won't work because it's 1 workflow and multiple diff files need to be generated, one per project (most of them likely empty).

## Potential solution - "master context"

A clean way to achieve that would be to have an ability to run commands in the context of base branch, for example with a `run-base` command that'd checkout main for this one command, or better use a cached version of main from a temporary subdir:

```
workflows:
  with-infracost:
    plan:
      steps:
        - init
        - plan
        - run-base: infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json
        - run: infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
```

**Comment by motatoes** [comment]
I think we can acheive this per project by performing the checkout within the digger.yml workflow_configuration. Something like this:

```
workflows:
  with-infracost:
    plan:
      steps:
        - init
        - plan
        - run: git checkout master && infracost breakdown --path ${PROJECT_DIR} --format=json --outfile=/tmp-infracost-base-${PROJECT_NAME} && git checkout $DIGGER_PRBRANCH
        - run: infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
```

However for this variable interpolation to work we first need to impelent #674 with some sensible default variables and then this would work
