### ISSUE TITLE
Digger apply fails to download artifact (plan file) from GitHub

### ISSUE THREAD

**Issue by damjanlepcheski** [diggerhq/digger#1068]
In our setup we specify 'github' as destination for the tfplan files. So when I run `digger plan`, the plan file is successfully attached to the PR with 'plan-$PRNUMBER.zip' name format. All good so far. 

However, when running `digger apply`, another `plan` is executed as part of the `digger run`, and this produced only local tfplan file, which is **not** uploaded to GitHub. When the `apply` step finally happens, it fails with the following errors:

```
Failed to run digger apply command. error retrieving plan: error downloading plan: failed to download artifact, status code: 400
Failed to run commands. error while running command: Failed to run digger apply command. <nil>
Error: Process completed with exit code 8.
```
When I remove the  `upload-plan-destination: 'github'` attribute from the workflow, `digger apply` is successful, likely because it is using the locally generated tfplan. 

### Additional helpful information 
- In the version I previously used (v0.2.0), `digger apply` successfully fetched the tfplan file from GitHub.
- Here's the workflow file I use:
```yaml
name: Digger
run-name: Digger on a Fargate hosted Github Actions Runner
on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.comment.body, 'digger')
    runs-on:
      labels: default
    permissions:
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
      actions: write       # required for artifact (plan) upload

    steps:
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: digger run
        uses: diggerhq/digger@v0.3.14
        with:
          setup-aws: false
          setup-terraform: true
          upload-plan-destination: 'github'
          no-backend: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
```

I'm happy to provide more info if necessary.
