### ISSUE TITLE
Backend: document the new input comment_id

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#1088]
There is a new input that needs to be in the workflows as of digger v0.3.17. Workflow Id needs to contain comment_id as input, since we have a new comments ux #1071 

```
name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: true
      comment_id:
        required: true
      job:
        required: true
```
