### ISSUE TITLE
digger not honouring terraform_version nor terraform-version, upgrades terraform states, always uses terraform latest

### ISSUE THREAD

**Issue by LucaIcaro** [diggerhq/digger#1118]
Hello everyone,

we noticed that all our terraform project have a state file between version 1.6.x and 1.7 even if we specify in every digger.yml this:

```
projects:
- name: dev-euw1
  dir: ./dev-euw1/
  terraform_version: v1.5.3
  include_patterns: ["../modules/**"]
```

I made some tests to find out if I was using the `terraform_version` wrong, but the documentation was not clear on that point.

I've also used an explicit `terraform-version` when calling the workflow

```
      - name: digger run
        uses: diggerhq/digger@v0.3.20
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          no-backend: true
          terraform-version: v1.5.3
```

but this hasn't triggered any kind of errors during the `terraform init` phase.

The only way to trigger an error was to explicitly add the terraform version in the provider
```
terraform {
 required_version = ">= 1.2.0, <= 1.6.6"
}
```

The only conclusion I can come about is that on both the digger.yml configuration file and on the action file the version is not honoured. 

Can you please advise? This has cause some problems, because we wanted to avoid forced updates to the terraform 1.7.

**Comment by LucaIcaro** [comment]
I just made a new very simple project that only creates a security group with this digger_workflow.yml:
```
      - name: digger run
        uses: diggerhq/digger@v0.3.20
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          no-backend: true
          # setup-terraform: true
          terraform-version: v1.5.3
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # here the workflow token is used implicitly
          GITHUB_OWNER: OUR_COMPANY
```

This comes from the log of `digger apply`:
```
Run diggerhq/digger@v0.3.20
  with:
    setup-aws: true
    aws-access-key-id: ***
    aws-secret-access-key: ***
    aws-region: eu-west-1
    no-backend: true
    terraform-version: v1.5.[3](https://github.com/Inivata/tf-app-aws-ec2-demo/actions/runs/7786138772/job/21230264153#step:4:3)
    setup-google-cloud: false
    setup-azure: false
    setup-terragrunt: false
    setup-opentofu: false
    terragrunt-version: v0.[4](https://github.com/Inivata/tf-app-aws-ec2-demo/actions/runs/7786138772/job/21230264153#step:4:4)8.[6](https://github.com/Inivata/tf-app-aws-ec2-demo/actions/runs/7786138772/job/21230264153#step:4:6)
    opentofu-version: v1.6.0-alpha3
```

but the state file of the project shows 
```
{
  "version": 4,
  "terraform_version": "1.7.2",
  "serial": 1,
  "lineage": "f8bc3a9e-bd57-c81e-4fa2-1afb6716aee1",
  "outputs": {},
  "resources": [
    {
```

**Comment by chvima** [comment]
```
      - name: digger run
        uses: diggerhq/digger@v0.3.20
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          no-backend: true
          terraform-version: v1.5.3
```

If you don't use setup-terraform:true, digger action is not installing terraform in the github runner env, see https://github.com/diggerhq/digger/blob/develop/action.yml#L215

I don't know your github runner environment setup, but I assume it has preinstalled v1.7.2 that it uses instead.
