### ISSUE TITLE
Perform better validation of digger.yml

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#114]
The following doesn't throw any warnings even though its invalid digger.yml, we need to ensure that at minimum a list of valid projects is defined in the digger.yml otherwise we throw an error

```
project:
  name: terraform-monorepo
services:
  project_a_d:
    service_name: project_a_d
    path: ./project_a/development
  project_a_n:
    service_name: project_a_n
    path: ./project_a/non-production
  project_a_p:
    service_name: project_a_p
    path: ./project_a/production
  project_a_s:
    service_name: project_a_s
    path: ./project_a/shared
  project_b_d:
    service_name: project_b_d
    path: ./project_b/development
  project_b_n:
    service_name: project_b_n
    path: ./project_b/non-production
  project_b_p:
    service_name: project_b_p
    path: ./project_b/production
```
