### ISSUE TITLE
Include pattern in digger.yml ignores changes in .yaml file

### ISSUE THREAD

**Issue by chvima** [diggerhq/digger#1151]
Issue: include_patters in digger.yml do not work correctly for all file types.
 I assume they are setup to watch only .tf files? Haven't found anything about it in docu:
https://docs.digger.dev/howto/include-exclude-patterns

I'll explain on example. We are using following structure for some of the terraform modules:

Terraform files in - managed by Devops team:
`aws-account/env/application/resource/main.tf
`
Configuration files that are available for change for Development teams - are in different structure:
`config/env/resource-id.yaml
`
The terraform module _aws-account/env/application/resource/main.tf_ uses config file in _config/env/resource-id.yaml_ as a configuration of the module.

I wanted to use include pattern to manage these modules, as usually developers change only the _config/env/resource-id.yaml_ in the PR and this should trigger Digger management of the module _aws-account/env/application/resource/main.tf_

I have used following config in digger.yml
```
projects:
 - name: p1
   dir: aws-account/env/application/resource/main.tf
   include_patterns: ["config/env/resource-id.yaml"]
```

But in case the PR is opened with a change in "config/env/resource-id.yaml" file, digger is not triggered.
Can the include_patterns be setup to trigger digger on change in any file?

**Comment by motatoes** [comment]
Hey @chvima as far as I can tell there is no file based filtering going on. We do use [doublestar](https://github.com/diggerhq/digger/blob/b18f982cf41985b040a24e1f84407a3ece15fac3/libs/digger_config/utils.go#L29) library and I'm not sure if it will perform exact file match without pattern. Could you try this and see if it ends up detecting ?

```
projects:
 - name: p1
   dir: aws-account/env/application/resource/main.tf
   include_patterns: ["config/env/*.yaml"]
```

If that works for you we need to look into exact match as well
