### ISSUE TITLE
Detect the dependencies between  projects NOT detecting the common directory

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#1158]
project autodetection, how to detect the dependencies between  NOT detecting the. common directory inside and also being able to figure out that there are dependencies and are common

> also tried detection
we organise by services, and env underneath. and common modules shared across dev/stg/prod workspace. and external modules
if I use projects as glob patterns; it also picks up on modules
BUT doesn't pick up dependencies - I need to say it xplicitly define a project and ALL of its dependencies
I'm looking to write a parser that goes over Terraform
if Digger could provide smth? woud add a TON of value

Reported by user N.L.

**Comment by wizardist** [comment]
Hey @ZIJ,

Is this issue the same as the problem I'm trying to solve?

Let's consider the following structure:

```
/
├── dev
│   └── local-slop <-- make-slop
├── modules
│   ├── brew-tea
│   ├── make-slop
│   └── be-good
├── stage
│   ├── cloud1
│   │   ├── app1 <-- brew-tea
│   │   └── app2 <-- be-good
│   └── cloud2
│       ├── app1 <-- brew-tea
│       └── app3 <-- be-good
└── prod
    ├── cloud1
    │   ├── app1 <-- brew-tea
    │   └── app2 <-- be-good
    └── cloud2
        ├── app1 <-- brew-tea
        └── app3 <-- be-good
```

The directories in `modules/` contain reusable modules. They don't get planned or applied themselves.

And the following project generators:

```yaml
generate_projects:
  blocks:
    - block_name: dev-projects
      include: "dev/**"
      opentofu: true
      root_dir: dev
      workflow: default
      workflow_file: digger.yml

    - block_name: stage-projects
      include: "stage/**"
      opentofu: true
      root_dir: stage
      workflow: default
      workflow_file: digger.yml

    - block_name: prod-projects
      include: "prod/**"
      opentofu: true
      root_dir: prod
      workflow: default
      workflow_file: digger.yml
```

And let's consider that in a given PR we only touch the reusable module `brew-tea`. With the given generator configuration, digger doesn't trigger planning for `app1` in either environment.

Now let's add `include_patterns: ["modules/**"]` to each block. Immediately we can see that digger will trigger planning. However, it will plan not just `app1` in all environments (correct on its own), but also `app2` and `app3` that didn't receive any changes – they don't depend on the `brew-tea` module. Likewise, `local-slop` plan was triggered.

I went back and forth through the documentation, including [project generators](https://docs.digger.dev/ce/howto/generate-projects), the [digger.yml reference](https://docs.digger.dev/ce/reference/digger.yml), and so on. Can't quite put my finger on what would be the solution here.

Is detection of such changes actually supported? So far the workaround we came up with is to declare the projects one by one and do a bit of double-entry bookkeeping by listing module dependencies explicitly in digger.yml.
