### ISSUE TITLE
Sub-directories not found in generate_projects.block glob search

### ISSUE THREAD

**Issue by ri-roee** [diggerhq/digger#1225]
I have the following `digger.yml` config, with the aims of generating a project for each `main.tf` in my root directory. However at runtime digger is only able to find the project at the root of the directory. Is this a bug with the glob search or am I misconfiguring the `include`? Thanks in advance!

```
generate_projects:
  blocks:
    - include: "deployments/aws/my_cluster/**"
      aws_role_to_assume:
        state: <arn1>
        command: <arn2>
```

```
deployments
-- aws
---- my_cluster
------ main.tf
------ sub-dir
-------- main.tf
------ sub-dir2
-------- folder
---------- main.tf
```
