### ISSUE TITLE
Make digger traversal configurable

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#1227]
In #1225 an issue is encountered because digger stops traversal at the first terraform found and does not traverse further. Lets make this option configurable by the user

- 
```
generate_projects:
  blocks:
    - include: "deployments/aws/my_cluster/**"
      aws_role_to_assume:
        state: <arn1>
        command: <arn2>
```

```

deployments
-- aws
---- my_cluster
------ main.tf
------ sub-dir
-------- main.tf
------ sub-dir2
-------- folder
---------- main.tf
```

Leads to only my-cluster detected. We can add a flag traverse_to_nested_projects (false by default) and if set to true will lead to all subdirectories detected:

my-cluster
Sub-dir
Subdir-2
