### ISSUE TITLE
digger.yml env_var workflow value_from returnes empty variable

### ISSUE THREAD

**Issue by raouf-xh** [diggerhq/digger#1319]
When using digger.yml **env_var** workflow to remap environment variable set from GitHub secrets to **TF_VAR** variable using command **value_from** to be used during terraform plan/apply, it always returns as an empty variable.
 
 digger.yml
 `workflows:
  default:
    env_vars:
      state:
        - name: TF_VAR_test_variable
          value_from: TEST_VARIABLE
      commands:
        - name: TF_VAR_test_variable
          value_from: TEST_VARIABLE

    plan:
      steps:
        - run: |
              echo "$TEST_VARIABLE"
        - init
        - plan`
        
   digger_workflow

```
        uses: diggerhq/digger@v0.4.13
        with:
          setup-aws: true
          aws-role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.REGION }}
          digger-hostname: 'https://cloud.digger.dev/'
          digger-organisation: 'digger'
          digger-token: ${{ secrets.DIGGER_TOKEN }}
          setup-checkov: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_VARIABLE: ${{ secrets.TEST_VARIABLE }}
```
          
  Terraform output 
```
  Changes to Outputs:
  + test_variable = [
      + "",
    ]
```

**Comment by raouf-xh** [comment]
Hi @motatoes ,
Yes it is working now but only if the project name is the same as the project workflow in digger.yml, having multiple projects (with different names) using the same workflow will result in an empty value of the TF_VAR variable.
Probably it's because the workflow is defined based on the project name here https://github.com/diggerhq/digger/pull/1413/commits/75c45f6835ee9c7636f0d0dc6f7dc8de15f74c0c

**Comment by raouf-xh** [comment]
The orchestrator doesn't pass the workflow name to the job, rather it passes the steps within it to the serialized JSON in CLI. 
Maybe passing the workflow name and changing the override the values based on it could fix the issue ?

This may also be a possible fix for the runner logs which doesn't state which workflow is using
`Override the values of StateEnvVars and CommandEnvVars from workflow value_from values`

**Comment by noxjonas** [comment]
encountering the same issue as @raouf-xh when using workflow that is named differently to the project.

for now I'm working around this using yaml anchors and aliases, perhaps will be useful for others:
```
defs:
  - workflow: &workflow
      env_vars:
        commands:
          - name: ABC
            value_from: XYZ

projects:
  - name: one
    dir: one
    workflow: one
  - name: two
    dir: two
    workflow: two

workflows:
  one:
    <<: *workflow
  two:
    <<: *workflow
```
