### ISSUE TITLE
Assume role per project not working with terragrunt generation (block)

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#1331]
I’m trying to generate terragrunt project but also be able to assume different roles for specific projects, but I can’t get the roles to switch. I’m guessing something is wrong with my digger.yml, I’m not sure how how to combine terragrunt_parsing block with aws_role_to_assume. Any help would be appreciated :bow:
This is how my digger.yml looks like

```
generate_projects:
  terragrunt:true
  terragrunt_parsing:
    parallel: true
    createProjectName: true
    createWorkspace: true
    defaultWorkflow: default
  blocks:
    - exclude: "environments/dr/**"
    - exclude: "environments/prd/**"
    - exclude: "environments/stg/**"
    - include: "environments/dev/**"
      aws_role_to_assume:
        state: "arn:aws:iam::45678:role/deployment-role"
        command: "arn:aws:iam::45678:role/deployment-role"
    - include: "environments/shared_services/**"
      aws_role_to_assume:
        state: "arn:aws:iam::12345:role/deployment-role"
        command: "arn:aws:iam::12345:role/deployment-role"
```

Reported by user I.P.

**Comment by viatcheslavmogilevsky** [comment]
This example doesn't work as well: https://docs.digger.dev/ce/reference/digger.yml?share_chat=6c264205-aa23-4b5e-972e-5f75125d7085

in digger workflow:

```yaml
- name: digger run
  uses: diggerhq/digger@vLatest
  with:
    digger-spec: ${{ inputs.spec }}
    setup-aws: true
    mode: drift-detection
    aws-role-to-assume: arn:aws:iam::{AccountID}:role/{RoleName}
    aws-region: us-east-1
```


in digger.yml:

```yaml
generate_projects:
  blocks:
    - include: "environments/core/**"
      aws_role_to_assume:
        aws_role_region: "us-east-2" 
        state: "arn:/blabla/accid/backenddev"
        command: "arn:/blabla/accid/devaccount"
```



My expectations digger-cli assumes `arn:/blabla/accid/backenddev` IAM role  just as is, using credentials from `arn:aws:iam::{AccountID}:role/{RoleName}` if they exists, but it seems it tries to assume `arn:/blabla/accid/backenddev` IAM role  using `AssumeRoleWithWebIdentity` and it fails:

```
Failed to get keys from role (StateEnvProvider): populateKeys: Could not retrieve keys from provider failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 2be6a9e7-e623-4796-ac23-8a220fa769c5, InvalidIdentityToken: No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com/
failed to fetch AWS keys, failed to get (state) keys from role: populateKeys: Could not retrieve keys from provider failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 2be6a9e7-e623-4796-ac23-8a220fa769c5, InvalidIdentityToken: No OpenIDConnect provider found in your account for
```

**Comment by viatcheslavmogilevsky** [comment]
Workaround (for terragrunt) is:


```yaml
generate_projects:
  blocks:
    - include: "environments/core/**"
       workflow: example
       terragrunt: true
workflows:
   example:
      state:
        - name: TERRAGRUNT_IAM_ROLE
          value: "arn:/blabla/accid/backenddev"
      commands:
        - name: TERRAGRUNT_IAM_ROLE
          value: "arn:/blabla/accid/devaccount"
```
