### ISSUE TITLE
Support terragrunt generation blocks

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#1382]
Currently for terragrunt generation we only support single terragrunt hierarchy per repo:

```
generate_projects:
  terragrunt_parsing:
    parallel: true
    createProjectName: true
    createWorkspace: true
    defaultWorkflow: default
```

Idea is to support it for monorepo structure where we have multiple terragrunt hierarchies per repo. We can use the same "blocks" structure that we have for normal terraform generation, but it would have a flag of `terragrunt: true` for every block, and accept the same arguments as normal terragrunt parsing:

```
generate_projects:
  blocks:
    aws-dev:
      terragrunt: true
      rootDir: "aws/dev"
      parallel: true
      createProjectName: true
      createWorkspace: true
      defaultWorkflow: default
      
    aws-prod:
      terragrunt: true
      rootDir: "aws/prod"
      parallel: true
      createProjectName: true
      createWorkspace: true
      defaultWorkflow: default
```
