### ISSUE TITLE
Drift Detection aws-assume-role is still not quite right

### ISSUE THREAD

**Issue by JoshuaJackson-jobvite** [diggerhq/digger#1386]
So we did an attempted fix for aws-assume-role based on some understanding and while we get much closer to the result we want/need to do approriate drift detection its off in a fundemental way that still needs a bit of investigation.

This is a continuation of https://github.com/diggerhq/digger/issues/1133. So instead of just failing completely, we do attempt to authenticate but the information we're gathering/passing is inaccurate as seen in the logger example here:

```
00:03:37 aws.go:50: Failed to get keys from role: populateKeys: Could not retrieve keys from provider WebIdentityErr: failed fetching WebIdentity token: 
caused by: Get "&audience=sts.amazonaws.com": unsupported protocol scheme ""
00:03:37 digger.go:551: failed to fetch AWS keys, Failed to get (state) keys from role: populateKeys: Could not retrieve keys from provider WebIdentityErr: failed fetching WebIdentity token: 
caused by: Get "&audience=sts.amazonaws.com": unsupported protocol scheme ""
```

So we're attempting auth, just the content we're attempting to pass is not correct. I've not had a chance to dive in deeper on this but unfortunately we are still missing something that we thought was the core of the issue we tried to fix in 1133.

**Comment by motatoes** [comment]
This might be a misconfiguration in the workflow itself. Out of curiousity you could try to do it with setup-aws: true in the digger step, since there might be some env vars that are not set causing golang aws sdk to throw this

**Comment by motatoes** [comment]
well, you might wanna try the version I'm about to release since it has an aws v1 to v2 upgrade so might help

**Comment by motatoes** [comment]
it would help for repo if you shared workflow and simple digger yml

**Comment by JoshuaJackson-jobvite** [comment]
workflow:
```
name: Digger Drift Detection

on:  
  workflow_dispatch:
  schedule: ## 12am monday.
    - cron: '0 0 * * 1'

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    steps:
    # create a temp. token from the github app installed in the org.
    # The app needs to have read access to all private terraform repos  in the org
    # this token is used in the next step to allow cloning terraform module repos
    - name: Generate Token
      id: generate_token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.secret2 }}
        private_key: ${{ secrets.secret1 }}
    # allow terraform to download our private modules
    - name: Set git config
      run:  /usr/bin/git config --global --add url."https://github:$GITHUB_TOKEN_READ_REPOS@github.com/company".insteadOf https://github.com/company
      env:
        GITHUB_TOKEN_READ_REPOS: ${{ steps.generate_token.outputs.token }}
    - name: digger drift detection
      uses: diggerhq/digger@latest
      with:
        mode: drift-detection
        setup-aws: false
        no-backend: true
        disable-locking: true
        digger-token: ${{ secrets.DIGGER_TOKEN }}
        digger-organisation: 'company'
        digger-hostname: https://cloud.digger.dev/
        drift-detection-slack-notification-url: 'hookurl'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_OWNER: Company
 ```
 
 
 digger.yml
 
 ```
 generate_projects:
  blocks:
    - include: "environments/core/**"
      workflow: default_work_flow
      aws_role_to_assume:
        state: "arn:aws:iam::XXXXXX:role/XXXXX-digger_terraform_state_iam_role"
        command: "arn:aws:iam::XXXXX:role/XXXXX-digger_iam_role"
    - include: "environments/cicd/**"
      workflow: default_work_flow
      aws_role_to_assume:
        state: "arn:aws:iam::XXXXXX:role/XXXXX-digger_terraform_state_iam_role"
        command: "arn:aws:iam::XXXXX:role/XXXXX-digger_iam_role"


telemetry: false
auto_merge: true

workflows:
  default_work_flow:
    plan:
      steps:
        - init
        - plan
        - run: infracost breakdown --path=. | tee -a $DIGGER_OUT
    apply:
      steps:
        - init
        - apply
    workflow_configuration:
      on_pull_request_pushed: ["digger plan"]
      on_pull_request_closed: ["digger unlock"]
      on_commit_to_default: ["digger apply"]
