### ISSUE TITLE
Error while running digger with Azure and OIDC credentials

### ISSUE THREAD

**Issue by 0xmrwn** [diggerhq/digger#1418]
Wondering if anyone managed to run a full workflow via GH Actions on Azure using OIDC credentials, and willing to share the configuration as documentation is a bit outdated (#665). Azure login seems to work fine but i'm stuck on this error when trying to run `diggerhq/digger@v0.4.20`. Accessing the lock table in Azure Storage is also impossible using OIDC.

> Can't really contribute on fixing this in the Go codebase, but I'd be happy to revamp the Azure docs section if the issue is sorted.

```txt
Using GitHub.
GitHub context parsed successfully
Digger digger_config read successfully
Failed to report project dummy_project. unexpected status when reporting a project: 403
Following projects are impacted by pull request #3
- dummy_project

GitHub event processed successfully
GitHub event converted to commands successfully
Following commands are going to be executed:
project: dummy_project: commands: "digger plan", 
Error while fetching policy: unexpected response while fetching project policy: Could not find bearer token in Authorization header code 403
Failed to run commands. error checking policy: unexpected response while fetching project policy: Could not find bearer token in Authorization header code 403
```

# My current setup
- An app registration and a service principal on Azure
- a storage account for tf backend
- a storage account for digger lock table
- `Storage Blob Data Contributor` role assigned to the sp and scoped on both storage accounts
- Federated credentials set on Azure for the service principal with `entity` set to Pull Request
  
## GHA Workflow .yml
```yml
name: Digger CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: digger run ${{github.event.inputs.id}}
        run: echo digger run ${{ inputs.id }}
        shell: bash      
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@v0.4.20
        with:
          disable-locking: false
          upload-plan-destination: github
          setup-azure: true
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          LOCK_PROVIDER: azure
```

## `digger.yml`
```yml
auto_merge: true
projects:
- name: dummy_project
  dir: dummytf
  workflow: dummy_workflow
workflows:
  dummy_workflow:
    env_vars:
      state:
        - name: TF_VAR_azure_client_id
          value_from: AZURE_CLIENT_ID
        - name: TF_VAR_azure_tenant_id
          value_from: AZURE_TENANT_ID
        - name: TF_VAR_azure_subscription_id
          value_from: AZURE_SUBSCRIPTION_ID
      commands:
        - name: TF_VAR_azure_client_id
          value_from: ARM_CLIENT_ID
        - name: TF_VAR_azure_tenant_id
          value_from: ARM_TENANT_ID
        - name: TF_VAR_azure_subscription_id
          value_from: ARM_SUBSCRIPTION_ID
    workflow_configuration:
      on_pull_request_pushed: ["digger plan"]
      on_pull_request_closed: ["digger unlock"]
      on_commit_to_default: ["digger unlock"]
```
