### ISSUE TITLE
Bug:  - GitHub Action CI Backendless mode + Terragrunt will cause a segmentation fault

### ISSUE THREAD

**Issue by ben-of-codecraft** [diggerhq/digger#1423]
## Steps to recreate
1. Use digger config 

digger.yaml
```yaml
projects:
- name: dev
  dir: dev
  terragrunt: true
  
  ```
  
  2. use workflow config 
  ```yaml
  name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
      comment_id:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      statuses: write

    steps:
    - uses: actions/checkout@v4
    - name: digger run
      uses: diggerhq/digger@v0.4.19
      with:
        setup-aws: true
        setup-terragrunt: true
        setup-checkov: false
        aws-role-to-assume: "REDACTED"
        no-backend: true
        aws-region: us-west-2
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ```
  
  
![image](https://github.com/diggerhq/digger/assets/110695027/f058ac66-9724-461f-b7e1-d884cd2475e7)
