### ISSUE TITLE
Bring back support for the branch option in digger.yml

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#1473]
It was listed here: https://docs.digger.dev/howto/workspaces
Removed as it is not supported at the moment
Consider re-introducing

**Comment by GLEF1X** [comment]
Hey there! Compared to Atlantis and others, Digger is a great tool! I was trying to find some docs around how to use digger with workspaces but seems like this section of docs was removed. Is there currently a workaround for using workspaces with branches?

My config:
```yml
projects:
  - name: production
    dir: infra
    workspace: prod
  - name: dev
    dir: infra
    workspace: dev
```
