### ISSUE TITLE
Add an additional  role arn config of "plan"  to aws_role_to_assume 

### ISSUE THREAD

**Issue by ben-of-codecraft** [diggerhq/digger#1482]
I would like to have an additional role that can be used for terra* plan vs terra* apply.  The rationale behind this since providers can do many things, one could exfiltrate the AWS environment credentials by simply submitting a PR.  If we can have a special plan role, then that can be read-only vs. having access to change resources. This would help reduce the threat of a PR being used to exfiltrate a more privileged role.

```yaml
    - name: "{{github.org}}-{{github.repo}}-prod"
      dir: prod
      workflow: default
      include_patterns: [
        "./modules/**",
        "./config/prod/**",
      ]
      workflow_file: digger_workflow.yml
      aws_role_to_assume:
        state: {{output.stsStateRole.prod}}
        command: {{output.stsCommandRole.prod}}  
        plan: {{output.stsPlanRole.prod}}.    ### This role should only have read access to resources that will be affected by the command role. 
        
 ```
