### ISSUE TITLE
Add the ability to support custom workflows 

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#149]
requested by @fleroux514 

Regarding worklflow configurations:
https://github.com/diggerhq/digger/blob/main/pkg/digger/digger_config_test.go#L91-L97
We need the ability to specify custom commands when terraform plan runs. In our case we would need to run https://github.com/bridgecrewio/checkov with all terraform plans to validate the TF configuration.

Something like this 

```
workflows:
  default:
    plan:
      steps:
      - init
      - plan:
          extra_args: ["-var-file=terraform.tfvars"]
      - run:
          cmd: "checkov --config-file ./.checkov.yml -d ./artifact_registries/shared/"
```

could be any command, executed in the order defined in the workflow.
