### ISSUE TITLE
Document the additional arguments needed in the workflow file

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#1546]
In #1543 we have supported dynamic names for workflows. This is a breaking change since anyone who upgrades will need to also update their workflow files to include the additional inputs `run_name`:

```
name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
      run_name:
        description: 'the run name'
        required: false
```

furthermore, they will also need to include a `run-name` argument in their workflow to benifit from this change:

```
run-name: '${{inputs.run_name}}'
```

We need to make sure that all the documentation is updated to reflect this and also add a troubleshooting guide for when errors such as this do exist for the unaware:

```
422 unexpected input of type "project_name"
```
