### ISSUE TITLE
Digger reports success even though Terraform apply fails

### ISSUE THREAD

**Issue by peteher** [diggerhq/digger#1658]
### Problem:
Terraform apply reports error/exit code 1, but pipeline won't fail as Digger saying "success"

### Setup:
- no-backend setup
- terraform 1.5.7
- digger vLatest today - v0.6.33
- upload-plan-destination: github
- digger.yaml:
```
projects:
  - name: default
    workflow: my_custom_workflow
workflows:
  my_custom_workflow:
    workflow_configuration:
      on_pull_request_pushed: [ digger plan ]
      on_pull_request_closed: [ digger unlock ]
      on_commit_to_default: [ digger apply ]
auto_merge: false
collect_usage_data: false
```
### Flow:
1. changes delivered to branch, PR (ie tag resources)
2. action runs to "plan" for PR
3. plan.out attached to action
4. make change on infra via console for eg delete a resource that the plan wants to tag
5. merge PR to "apply"
6. Terraform apply will fail as step 1 change can't be committed on step 4 removed resource
7. Digger would say "apply failed, skipping job" and "success" - pipeline finishing green ✅ - I'd expect ❌ 

![image](https://github.com/user-attachments/assets/dc24057b-b9b3-4c2f-b5bc-a819ecae7a54)

Using version v0.3.22 I get the expected fail:
![image](https://github.com/user-attachments/assets/098ae236-e7e3-42f6-a25e-dcab7ab7cc05)
