### ISSUE TITLE
Drift detection is reporting non-drifting modules

### ISSUE THREAD

**Issue by noisyscanner** [diggerhq/digger#1667]
See notifications posted to our Slack below:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/bcf7c29b-6151-490d-b77c-2fd1505e23c4">

Workfow:
```yaml
name: Digger Drift Detection

on:
  # workflow_dispatch:
  # schedule: ## 12am daily.
  #   - cron: '0 0 * * *'
  push:
    branches:
      - drift

permissions:
  contents: read
  id-token: write # for aws oidc

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    steps:
    - name: digger drift detection
      uses: diggerhq/digger@vLatest
      with:
        mode: drift-detection
        no-backend: true
        cache-dependencies: true
        setup-aws: true
        aws-role-to-assume: <my-role-arn>
        aws-region: eu-west-2
        drift-detection-slack-notification-url: ${{ secrets.DRIFT_DETECTION_SLACK_NOTIFICATION }}

        setup-opentofu: true
        opentofu-version: v1.6.2

        setup-terragrunt: true
        terragrunt-version: 0.66.3
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

CC @motatoes
