### ISSUE TITLE
Digger apply being applied from the main and not from my PR

### ISSUE THREAD

**Issue by lucaassoaares** [diggerhq/digger#1682]
I have a pipeline that executes the digger plan as soon as I successfully open the PR. But when I comment 'digger apply', it executes the pipeline that is in main and not the pipeline in my Branch. This is causing my checks to fail when executing apply.

```
name: Digger

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  apply:
    name: Digger apply
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set_envs.outputs.ENVIRONMENTS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
   
      - name: Get list of changed files
        id: changed-files
        run: |
            git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
            git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > changed_files.txt

      - name: Set environments
        id: set_envs
        run: |
          environments=()
          unique_environments=()
          all_environments=("dev")
          tf_file_changed=false

          while IFS='' read -r file; do
            if [[ "$file" =~ \.tf$ ]]; then
              tf_file_changed=true
            elif [[ "$file" =~ \.tfvars$ ]]; then
              # Extrair o nome do ambiente após o último '/'
              env_name=$(basename "$file" .tfvars)
              if [[ ! " ${unique_environments[*]} " =~ " ${env_name} " ]]; then
                environments+=("$env_name")
                unique_environments+=("$env_name")
                echo "Adding unique environment: $env_name"
              fi
            fi
          done < changed_files.txt

          if [[ "$tf_file_changed" == true ]]; then
            # Adicionar todos os ambientes se qualquer arquivo .tf foi modificado
            environments=("${all_environments[@]}")
          fi

          # Converter o array 'environments' to JSON jq
          environments_json=$(printf "%s\n" "${environments[@]}" | jq -Rsc 'split("\n")[:-1]')
          echo "ENVIRONMENTS=$environments_json" >> $GITHUB_OUTPUT
          echo "Final environments: $environments_json"

  run_matrix:
    needs: apply
    runs-on: ubuntu-latest
    strategy:
      matrix:
         environment: "${{ fromJson(needs.apply.outputs.environments) }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set GCP Credentials Secret
        id: set-gcp-credentials
        run: |
           if [[ "${{ matrix.environment }}" == "dev" ]]; then
            gcp_credentials=$(echo '${{ secrets.GCP_CREDENTIALS_DEV }}' | jq -c .)
            bucket_name="name"
            elif [[ "${{ matrix.environment }}" == "prod" ]]; then
              gcp_credentials=$(echo '${{ secrets.GCP_CREDENTIALS_PROD }}' | jq -c .)
              bucket_name="name"
            else
              echo "Unsupported environment: ${{ matrix.environment }}"
              exit 1
            fi
            echo "GCP_CREDENTIALS=$gcp_credentials" >> $GITHUB_OUTPUT
            echo "GCP_BUCKET=$bucket_name" >> $GITHUB_OUTPUT

      - name: create-json
        id: create-json-dev
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "gcs.json"
          json: '${{ steps.set-gcp-credentials.outputs.GCP_CREDENTIALS }}'
          dir: 'gcp/'

      - name: digger plan
        uses: diggerhq/digger@vLatest
        with:
            no-backend: true
            setup-google-cloud: true
            google-auth-credentials: ${{ steps.set-gcp-credentials.outputs.GCP_CREDENTIALS }}
            google-lock-bucket: ${{ steps.set-gcp-credentials.outputs.GCP_BUCKET }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCK_PROVIDER: gcp
          ENVIRONMENT: ${{ matrix.environment }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.USER }}
```

Can you help me please? Are there any settings missing?
Could there be something wrong with using no-backend: true?

**Comment by lucaassoaares** [comment]
```
generate_projects:
  blocks:
    - include: "gcp/**"
      workflow: maravi
      workspace: $ENVIRONMENT

workflows:
  maravi:
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
    plan:
      steps:
        - init:
            extra_args: ["-backend-config=backend/$ENVIRONMENT.hcl"]
        - plan:
            extra_args: ["-var-file=environments/$ENVIRONMENT.tfvars"]
        - run: |
            infracost breakdown --path=. | tee -a $DIGGER_OUT
    apply:
      steps:
        - init:
            extra_args: ["-backend-config=backend/$ENVIRONMENT.hcl"]
        - run
        - apply:
            extra_args: ["-var-file=environments/$ENVIRONMENT.tfvars"]
```
