### ISSUE TITLE
Terragrunt - AwsAssumeRole does not work on generate_projects / blocks configuration - Community Edition

### ISSUE THREAD

**Issue by ben-of-codecraft** [diggerhq/digger#1714]
### Issue 
When using backendless action inputs:
```yaml
      - name: digger run
        uses: diggerhq/digger@v0.6.39
        with:
            setup-aws: false
            setup-terragrunt: true
            setup-checkov: false
            disable-locking: true
            no-backend: true
            terragrunt-version: 0.50.2
```

The command/state role assumes do not get used correctly when set on the blocks like as follows

```yaml
generate_projects
    blocks:
      - block_name: dev
        terragrunt: true
        root_dir: "dev/"
        workflow: default
        workflow_file: digger_workflow.yml
        aws_role_to_assume:
           aws_role_region: "us-east-1"
           command: "xxxx"
  
```

### Expected Behavior

AWSRole identity provider is used and passed into Terragrunt run similar to to how Terraform works.
