### ISSUE TITLE
auto-merge is not working for terragrunt projects

### ISSUE THREAD

**Issue by carcunha** [diggerhq/digger#1822]
I have digger configured for a few terraform standalone project with `auto_merge: true` just working, but on a couple of terragrunt ones, it's just not working.

Here is the configuration:
```yaml
---
auto_merge: true
generate_projects:
  terragrunt: true
  terragrunt_parsing:
    parallel: true
    createProjectName: true
    defaultWorkflow: default
    ignoreDependencyBlocks: true
```

and here is the output of the apply:
```hcl
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:
*******

no $DIGGER_OUT file at: /home/runner/work/_temp/digger-out.log
Commands executed successfully
Digger finished successfully
