### ISSUE TITLE
azure: setting different credentials per project and storage account per project

### ISSUE THREAD

**Issue by abazzi-neogenomics** [diggerhq/digger#1945]
Hi guys,

I need to set different credentials (trying azure right now, but i guess the same issue would apply to aws or gcp) per project, i thought i'd skip passing the vars that change per sub in the workflow like this"

```
<cut>
        - name: digger run
          uses: diggerhq/digger@v0.3.27
          with:
            no-backend: true
            setup-terraform: true
            setup-azure: true
            terraform-version: ${{ inputs.TF_VERSION }}
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
            GITHUB_OWNER: Inivata
            LOCK_PROVIDER: azure
            DIGGER_AZURE_AUTH_METHOD: CLIENT_SECRET
            # DIGGER_AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_SANDBOX }}
            # DIGGER_AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_SANDBOX}}
            DIGGER_AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            # DIGGER_AZURE_SA_NAME: "stmysotrageaccounttfstate"
 ```

(i redacted some stuff but you get the idea)

and pass them in the config file like this:

```
projects:

- name: sandbox
  dir: ./sandbox/
  workflow: sandbox
  terraform_plan_args: "-var-file=terraform.tfvars"
  terraform_apply_args: "-var-file=terraform.tfvars"


workflows:

  sandbox:
    env_vars:
      commands:
        - name: DIGGER_AZURE_CLIENT_ID
          value: ${{ secrets.ARM_CLIENT_ID_SANDBOX }}
        - name: DIGGER_AZURE_CLIENT_SECRET
          value: ${{ secrets.ARM_CLIENT_SECRET_SANDBOX }}
        - name: DIGGER_AZURE_SA_NAME
          value: "stmysotrageaccounttfstate"

```

But I can't find a way for digger to pick them up, they are just unset.

How do i correctly configure different creds/storage accounts for different projects, if each project runs in a separate sub with a separate storeage account?

https://docs.digger.dev/ce/azure-specific/azure + https://docs.digger.dev/ce/reference/digger.yml i was basing my assumptions from this but if you have a better link please send it over :)

Thank you!
