### ISSUE TITLE
feature: global project defaults

### ISSUE THREAD

**Issue by dannysauer** [diggerhq/digger#1995]
As a user, I'd like to specify common project defaults once in the digger.yaml instead of duplicating across multiple projects.  For example:

```yaml
project_defaults:
- opentofu: true
  include_patterns:
    - ../../.tool-versions
    - ../../.github/workflows/digger_*.yml
```

This would set all projects to use opentofu, and specify two paths which should be merged with any project-specific include patterns. Presumably, `name` and `path` would be invalid in this section.  The `depends_on` parameter might be doable as long as "depends on self" is silently ignored. :)

Allowing specification of common attributes across multiple projects reduces boilerplate code, making it easier to read the config file without the cognitive load of identifying and skipping unimportant segments.  It also reduces the probability of error when adding a new project.
