### ISSUE TITLE
Support triggering project changes from other directories

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#210]
Scenario

directory structure looks like this:
```
modules/
dev/
staging/
prod/
```

digger.yml

```
projects:
- name: dev
  dir: dev
  workspace: dev
- name: staging
  dir: staging
  workspace: staging
- name: prod
  dir: prod
  workspace: prod
```

how to make digger trigger plan for all projects whenever the modules shared folder is updated? In Atlantis this is done using a `when_modified` parameter. We may wish to follow similar path and also support this parameter in digger.

**Comment by motatoes** [comment]
Agreed to implement it as the following:

```
projects:
  - name: gke_shared_cluster_dev
    dir: ./gke_shared_cluster/development
    dependent_modules: ["./modules/single_project"]
    workflow: default_workflow
  - name: gke_shared_cluster_non-prod
    dirs: ./gke_shared_cluster/non-production
    dependent_modules: ["./modules/single_project"]
    workflow: default_workflow
  - name: gke_shared_cluster_prod
    dir: ./gke_shared_cluster/production
    dependent_modules: ["./modules/single_project"]
```
