### ISSUE TITLE
multiple impacted projects should show separate status checks in the pull requests

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#213]
Consider a case such as this digger.yml

```
projects:
  - name: dev
    dir: ./dev
    workflow: devworkflow
  - name: staging
    dir: ./dev
    workflow: stagingworkflow

```

after PR is made in dev folder one job is started to create a plan called "dev/plan" , both plans are performed serially. if any one of them fails then the entire status of the job fails, and no comment is left in the PR. Due to this it can be difficult to debug this. since the two plans are printed out serially and no comment is issued in the PR itself.

Expectation:

There should be two statuses shown in the PR one for "dev" and the other for "staging". Furthermore the comment with failure should be posted in the pull request as well (?)
