### ISSUE TITLE
Workflow custom commands should be executed from the project directory by default

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#259]
For instance, with this digger.yaml config:

```
projects:
  - name: proj_a_dev
    dir: ./proj_a/development
    workflow: my_workflow
  - name: proj_a_prod
    dir: ./proj_a/production
    workflow: my_workflow
workflows:
  my_workflow:
    plan:
      steps:
      - init
      - plan
      - run: pwd
```

I would expect `pwd` to return the path to `./proj_a/development` and `./proj_a/production` when executed from both projects respectively. Currently it returns the root repo path.

Need this functionality to run commands like `checkov` in all projects.
