### ISSUE TITLE
Fail with clearer error message when digger.yml workflow is misconfigured

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#260]
Consider this digger.yml

```
projects:
  - name: dev
    dir: ./dev
    workflow: devworkflow

workflows:
  devworkflow:
    plan:
      steps:
      - run: "mv dev/dev.tfvars dev/dev.auto.tfvars"
      - init:
      - plan:
```

This is not a valid workflow since `init:` and `plan:` should be applied without any trailing columns, currently this fails in v18 with obscure error:

```
Error: Backend initialization required, please run "terraform init"
```

Better would be to fail earlier and say something like:

```
Invalid configuration, missing init found in `defaworkflow`, please ensure that you specify both init and plan in your configuration file
```
