### ISSUE TITLE
OIDC support for AWS

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#288]
Currently AWS access requires a AWS_SECRET_ACCESS_KEY 

https://github.com/diggerhq/digger_demo_workspaces/blob/main/.github/workflows/plan.yml#LL22C46-L22C67

It seems like the best practice now with AWS is to use openID like this: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Atm we only have federated access support (OIDC) for GCP - but not for AWS or Azure

Reported by @Lp-Francois

**Comment by frank-bee** [comment]
OICD for AWS works out of the box
For you need is :
- a role in AWS connected to github via OIDC
see https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
- a step in you workflow
```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::1111111111:role/github
          aws-region: eu-central-1
```
