### ISSUE TITLE
more strict validation of workflows block in digger.yml

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#298]
Currently digger does not fail when there is a mistake in workflow configuration like this:

```
projects:
- name: dev
  dir: dev
  workflow: common
- name: prod
  dir: prod
  workflow: common

workflows: 
  common:
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

should actually be:

```
projects:
- name: dev
  dir: dev
  workflow: common
- name: prod
  dir: prod
  workflow: common

workflow_configuration:
  common:
    on_pull_request_pushed: [digger plan]
    on_pull_request_closed: [digger unlock]
    on_commit_to_default: [digger apply]
```

Expectation: Digger should fail on run and complain about missing configuration

What happens: digger silently ignores the incorrect workflow configuration
