### ISSUE TITLE
Fix parsing error in digger.yml

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#326]
Version: v0.1.23-pre

Error:

```
Failed to read Digger config. failed to find workflow config 'default' for project 'ecr'
```

digger.yml

```
projects:
  - name: ecr
    dir: ecr
    terragrunt: true
  - name: ac2ical
    dir: app
    terragrunt: true
    workflow: ac2ical

workflows:
  ac2ical:
    env_vars:
      commands:
        - name: TF_VAR_ac_username
          value_from: AC_USERNAME
        - name: TF_VAR_ac_password
          value_from: AC_PASSWORD
````
