### ISSUE TITLE
terraform workspace fails to plan/apply when workspace already exists

### ISSUE THREAD

**Issue by annalisabazzi** [diggerhq/digger#349]
terraform plan (and apply) with the workspace feature seem to fail if the workspace already exists.

Scenario: code on github, existing project with 2 pre-existing terraform workspaces and remote states in s3.

digger.yml:

```
projects:
- name: shared
  branch: /test-branch/
  dir: ./terraform/
  workspace: shared
  terraform_version: v1.2.0
- name: dev
  branch: /test-branch/
  dir: ./terraform/
  workspace: dev
  terraform_version: v1.2.0
```

from cli:

```
[annalisa:.../tf-project/terraform]$ terraform workspace list
* default
  dev
  shared
```

digger output for plan (on pr in my case):

```
2023/06/07 15:21:01 Following projects are impacted by pull request #2
shared
dev
GitHub event processed successfully
GitHub event converted to commands successfully
2023/06/07 15:21:01 Following commands are going to be executed:
project: shared: commands: "digger plan", 
project: dev: commands: "digger plan", 
Lock annalisabazzi/tf-project#shared
2023/06/07 15:21:02 Lock result: true

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/template versions matching "~> 2.2"...
- Finding hashicorp/aws versions matching "~> 4.57"...
- Installing hashicorp/aws v4.67.0...
- Installed hashicorp/aws v4.67.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
default
Workspace "shared" already exists
Error: exit status 1
2023/06/07 15:21:14 Failed to run digger plan command. error executing plan: exit status 1
Failed to run commands. failed to run digger plan command. error executing plan: exit status 1
Error: Process completed with exit code 8.
```

Just for extra reference (although i believe it's not relevant), here the github workflow I'm using to test

```
name: DiggerCI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: digger run
        uses: diggerhq/digger@v0.1.23
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
