### ISSUE TITLE
unable to pass extra args to plan in github actions

### ISSUE THREAD

**Issue by annalisabazzi** [diggerhq/digger#352]
Hey guys, this may be a false positive, but I seem unable to pass extra args when planning (specifically tfvars)
I tried shuffling my code around but I'm stuck, maybe I didn't configure it properly?

This is the output I keep getting with all the configs I tried
**Important side note**:  @motatoes you can disregard the workspace line in these files, I forked your repo for #349 but before raising a PR I wanted to test it properly with and without workspaces.. the workspace selection works fine now on my fork, but I can't plan and apply due to this issue I'm having now so I don't feel like raising a PR that hasn't been properly tested

**output**

````
Switched to workspace "shared".
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: No value for required variable

  on vars.tf line 1:
   1: variable "account_alias" {

The root module input variable "account_alias" is not set, and has no default
value. Use a -var or -var-file command line argument to provide a value for
this variable.

Error: No value for required variable

  on vars.tf line 6:
   6: variable "assume_role_arn" {

The root module input variable "assume_role_arn" is not set, and has no
default value. Use a -var or -var-file command line argument to provide a
value for this variable.
2023/06/10 13:00:23 Failed to run digger plan command. error executing plan: exit status 1
Error: exit status 1
Failed to run commands. failed to run digger plan command. error executing plan: exit status 1
Error: Process completed with exit code 8.
````

Here the configurations I tried

1) inside terraform/vars/<deployment-name>.tfvars and then custom workflow named <deployment-name> with plan extra args -var-file=<deployment-name>.tfvars

```
.
├── digger.yml
└── terraform
    ├── backend.tf
    ├── naming.tf
    ├── providers.tf
    ├── resource.tf
    ├── tagging.tf
    ├── vars
    │   ├── dev.tfvars
    │   └── shared.tfvars
    └── vars.tf
```

**digger.yml:**

```
workflows:
  shared:
    plan:
      steps:
        - run: rm -rf .terraform
        - init
        - plan:
            extra_args: ["-var-file=vars/shared.tfvars"]

  dev:
    plan:
      steps:
        - run: rm -rf .terraform
        - init
        - plan:
            extra_args: ["-var-file=vars/dev.tfvars"]

projects:
- name: shared
  branch: /digger-test1/
  dir: ./terraform/
  workspace: shared
  terraform_version: v1.2.0
  workflow: shared
- name: dev
  branch: /digger-test1/
  dir: ./terraform/
  workspace: dev
  terraform_version: v1.2.0
  workflow: dev
```

2) I tried placing the vars directory *out* of the project like this:

```
.
├── digger.yml
├── terraform
│   ├── backend.tf
│   ├── naming.tf
│   ├── providers.tf
│   ├── resource.tf
│   ├── tagging.tf
│   └── vars.tf
└── vars
    ├── dev
    │   └── terraform.tfvars
    └── shared
        └── terraform.tfvars
```

**digger.yml:**

```
projects:
- name: shared
  branch: /digger-test1/
  dir: ./terraform/
  workspace: shared
  terraform_version: v1.2.0
  include_patterns: ["./vars/shared/**"]
- name: dev
  branch: /digger-test1/
  dir: ./terraform/
  workspace: dev
  terraform_version: v1.2.0
  include_patterns: ["./vars/dev/**"]
```

I also tried naming the vars: `terraform.tfvars, terraform.auto.tfvars, terraform.template.tfvars`
Same output, doesn't seem to pick up the -var-file
I tried this with and without the custom workflows, the snippet here is without, but I also tried with the custom workflow like in configuration 1) and I passed to plan extra_args `-var-file=vars/dev/<filename>.tfvars`, I tried also `-var-file=../vars/dev/<filename>.tfvars` cause i didn't know how the include was done, but no luck

Any idea?
