### ISSUE TITLE
on_commit_to_default workflow configuration not taken into account

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#358]
I manually merged https://github.com/diggerhq/francios-tests/pull/30

[digger.yml](https://github.com/diggerhq/francios-tests/blob/dev2/digger.yml) config:

```
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

Resulting workflow ran `digger unlock` instead of `digger apply`:  https://github.com/diggerhq/francios-tests/actions/runs/5244514381
