### ISSUE TITLE
Manual merge of a PR doesn't run `digger apply` properly

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#399]
Using digger@v0.1.25

My digger workflow is setup with 
```
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

I manually merged the PR and logs show the following:

```
2023/06/21 22:03:50 Following projects are impacted by pull request #571
artifact_registries_prod
gke_shared_cluster_dev
gke_shared_cluster_non-prod
gke_shared_cluster_prod
nlu_speech_science_dev
nu_workforce_dev
nu_workforce_non_prod
nu_workforce_prod
personal_projects_dev
website_corpo_prod
GitHub event processed successfully
GitHub event converted to commands successfully
2023/06/21 22:03:50 Following commands are going to be executed:
project: artifact_registries_prod: commands: "digger apply", 
project: gke_shared_cluster_dev: commands: "digger apply", 
project: gke_shared_cluster_non-prod: commands: "digger apply", 
project: gke_shared_cluster_prod: commands: "digger apply", 
project: nlu_speech_science_dev: commands: "digger apply", 
project: nu_workforce_dev: commands: "digger apply", 
project: nu_workforce_non_prod: commands: "digger apply", 
project: nu_workforce_prod: commands: "digger apply", 
project: personal_projects_dev: commands: "digger apply", 
project: website_corpo_prod: commands: "digger apply", 
Commands executed successfully
Digger finished successfully
```

But the apply did not actually happen  (even the logs don't show the apply results)
