### ISSUE TITLE
Example for gitlab ci file

### ISSUE THREAD

**Issue by lllsJllsJ** [diggerhq/digger#466]
First thanks for contrubute awssome tools.

I wondering if there are any example for gitlab ci file?
I have search thorugh document https://docs.digger.dev/getting-started/gitlab-pipelines-+-aws  and in the git repo
but it didn't mention how to setup .gitlab-ci.yml file.

**Comment by veziak** [comment]
Hi @lllsJllsJ , gitlab CI config file could look like this:
```
stages:
- digger

image: golang:1.20

install_digger:
  stage: digger
  script:
  - apt-get update && apt-get install -y gnupg software-properties-common
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt update
  - apt-get install terraform

  - git clone https://github.com/diggerhq/digger.git
  - cd digger
  - git checkout develop
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o digger ./cmd/digger
  - cd ..
  - ./digger/digger
```
you also need to configure gitlab webhooks with lambda: https://github.com/diggerhq/gitlab-webhook-lambda
