### ISSUE TITLE
Unable to pass env vars to terragrunt

### ISSUE THREAD

**Issue by noxjonas** [diggerhq/digger#477]
specifically trying to set `TERRAGRUNT_AUTO_INIT` env to `false`. In my setup the default principal that runs terragrunt does not have access to the remote states. But by default it tries to check for access, and digger workflow fails waiting for input for:
```Remote state S3 bucket <bucket> does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)```

So far I tried:
- specifying env vars at the root of workflow with: 
  ```env:
    TERRAGRUNT_AUTO_INIT: false
  ```
- adding it to `env:` to the digger run step
- adding it to `digger.yml` with:
  ```
  workflows:
    my_workflow:
      env_vars:
        - name: TERRAGRUNT_AUTO_INIT
          value: false
  ```

Also tried adding it the corresponding terragrunt cli flag to the plan step with:
```
workflows:
  my_workflow:
    plan:
      steps:
        - init
        - plan:
          extra_args: ["--terragrunt-no-auto-init"]
```

but no luck with any of these. is this expected behaviour so far or am I missing some issue with my configs? I can reproduce the above terragrunt behaviour locally and fix it using the above mentioned env var or cli flag.
