### ISSUE TITLE
Improved validation of digger.yml (generate_projects)

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#489]
We need to add extra validation for digger.yml for the key `generate_projects`

for example this digger.yml 

```
projects:
- name: xxx
  dir: "dev"
  workflow: tfci_stg_vpc
generate_projects:
  exclude: "../.terraform/**"
```

Should fail earlier since the `generate_projects` key does not have an `include` parameter
