### ISSUE TITLE
Improved validation of digger projects (workflow_configuration)

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#490]
digger.yml validation should fail if workflow configuration is empty or specified in the wrong location (since workflow configuration should contain all the three keys under it:

```
workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

for example the following digger.yml should fail

```
projects:
- name: xxx
  dir: "dev"
  workflow: myworkflow
generate_projects:
  exclude: "../.terraform/**"
workflows:
  myworkflow:
    plan:
      steps:
      - run: "checkov -d ."
      - init
      - plan
    apply:
      steps:
      - run: "terraform fmt -check -diff -recursive"
        shell: zsh
      - init
      - apply
    workflow_configuration:
```

specifying that workflow configuration should specify a list of `on_pull_request_pushed`, `on_pull_request_closed` and `on_commit_to_default` should all exist.
