### ISSUE TITLE
Support plugins: abillity to extend digger reporting system

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#529]
#485  and other requests include ability to see results of workflow tools such as infracost within the PR workflow. Proposal is to allow users to add more to the results of digger based on workflow configuration within digger.yml. 

Exact way to perform and API to be discussed with team

**Comment by thenonameguy** [comment]
Would recommend an approach similar to how Github Actions provides outputs:
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

So the user API would change from:
```yaml
workflows:
  project_a:
    plan:
      steps:
        - init
        - plan
        - run: infracost breakdown --path=.
```

to
```yaml
workflows:
  project_a:
    plan:
      steps:
        - init
        - plan
        - run: infracost breakdown --path=. | tee -a $DIGGER_OUTPUT
```
