### ISSUE TITLE
support terragrunt

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#54]
a config option that'd change behavior to run `terragrunt plan` and `terragrunt apply` command instead of `terraform`

**Comment by ZIJ** [comment]
Also needed by @AntonChekunov

**Comment by motatoes** [comment]
Hey @daanbosch apologies we need to get our docs in better shape! To answer your question about terragrunt, the way to get it done is by defining project for every environment, digger will only pick up changes that happen in `dir` folder:

```
projects:
- name: development
  dir: dev/
  terragrunt: true
- name: production
  dir: prod/
  terragrunt: true
```

Does this answer your question ?
