### ISSUE TITLE
Add show-projects command to CommentOps

### ISSUE THREAD

**Issue by toVersus** [diggerhq/digger#547]
It would be great to have a `digger show-projects` command to show all the impacted projects by the PR on the comment, and use that info to run other commands like `digger plan -p <project_name>` or `digger apply -p <project_name>` without looking at the digger.yaml file. We currently define a lot of projects in the digger.yaml file and cannot remember the relationship between `dir` and `name` of the project.

### Something like this

digger.yaml:

```yaml
projects:
- name: foo_develop
  dir: foo
  workflow: develop
- name: foo_staging
  dir: foo
  workflow: staging
- name: foo_product
  dir: foo
  workflow: product
- name: bar_develop
  dir: bar
  workflow: develop
- name: bar_staging
  dir: bar
  workflow: staging
- name: bar_product
  dir: bar
  workflow: product
- name: baz
  dir: baz
  workflow: default
...
```

GitHub comment output:

```
Following projects are impacted by pull request #999
- foo_develop
- foo_staging
- foo_product
- baz
```

If this feature request is acceptable, I will send the PR do the implementation. (WIP: https://github.com/toVersus/digger-lib-orchestrator/commit/10387e241c7c7ff28f4075b865c4c26229758120, https://github.com/toVersus/digger/commit/bf59142c84267f6b1a42efeeb357347d58d80245)
