### ISSUE TITLE
Restrict apply user

### ISSUE THREAD

**Issue by sat0ken** [diggerhq/digger#577]
Currently, every user who can write a comment `digger apply`,  can apply.
I think it can restricting execution by using `github.actor` context information.

For example, if action.yaml could be written as shown below, wouldn't it be possible to restrict the users who execute it?

```
    - uses: actions/checkout@v4
      with:
        clean: false
        ref: refs/pull/${{ github.event.issue.number }}/merge
      if: ${{ github.event_name == 'issue_comment' && inputs.configure-checkout == 'true' && github.actor == inputs.apply_user }}
```

https://github.com/diggerhq/digger/issues/272
