### ISSUE TITLE
Cannot exclude a folder from automatic project generation using Terragrunt

### ISSUE THREAD

**Issue by rtizzy** [diggerhq/digger#579]
Example config: 

```
generate_projects:
  include: "terraform/**"
  exclude: "**/secrets/**"
  terragrunt_parsing:
    parallel: true
    createProjectName: true
    createWorkspace: true
    defaultWorkflow: default

workflows:
  default:
    plan:
      steps:
        - init
        - plan
        - run: echo "Hello World"
```

In short I'm attempting to exclude any folder with the name `secrets` from the automatic project generation. 

I tried the above but it does not attempt to work. Am I holding this wrong?
