### ISSUE TITLE
Allow multiple dynamic project generates profiles with workflow configurable

### ISSUE THREAD

**Issue by zongsizhang** [diggerhq/digger#591]
it's quite typical for Atlantis users to mange repo in below architecture:
```prod/
  project-1/
  project-2/
staging: -> need a separate workflow, deploy to different aws account
  project-1/
  project-2/```

Currently in digger the only way is to manually clarify all the projects as generate projects all share the same default workflow config.

The most straight forward way is to enable multiple generate_preojects
```
generate_projects:
- includes: xxx
  excludes: xxx
- includes: xxx
  excludes: xxx
```

I suggest digger can enable us to clarify projects in any sub folders under the repo. In this case the main config file doesn't need to care about the project structure at all.
```
prod/
  digger.yml -> config differ
  project-1/
  project-2/
staging/
  digger.yml -> config digger
  project-1/
  project-2/

And make digger binary to discover the config files, and execute accordingly.

Much appreciate!

**Comment by motatoes** [comment]
Hi there! Thanks for filing the issue ..

Another idea I also have to keep everything toplevel is to enable workflow under each inc/udes/excludes pair as follows:

```
generate_projects:
    - includes: xxx
       excludes: xxx
       workflow: staging
    - includes: xxx
       excludes: xxx
       workflow: prod

workflows:
  staging:
    envs:
      state:
      - name: AWS_ACCESS_KEY_ID
        value_from: STAGING_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        value_from: STAGING_SECRET_ACCESS_KEY
      commands:
      - name: AWS_ACCESS_KEY_ID
        value_from: STAGING_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        value_from: STAGING_SECRET_ACCESS_KEY
  prod:
    envs:
      state:
      - name: AWS_ACCESS_KEY_ID
        value_from: PROD_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        value_from: PROD_SECRET_ACCESS_KEY
      commands:
      - name: AWS_ACCESS_KEY_ID
        value_from: PROD_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        value_from: PROD_SECRET_ACCESS_KEY

```
