### ISSUE TITLE
"on_commit_to_default" config fails to run correctly

### ISSUE THREAD

**Issue by fleroux514** [diggerhq/digger#593]
Testing using v0.1.32 with the following config:
```
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

Merging the PR manually fails with:

![image](https://github.com/diggerhq/digger/assets/17277004/8a6b1fdd-4d72-498d-aa11-3ee658007d11)

Probably because the Github repo is setup to delete remote branches when they are merged.
