### ISSUE TITLE
Support injecting default environment variables into steps

### ISSUE THREAD

**Issue by joerg** [diggerhq/digger#674]
Atlantis supports injecting certain default environment variables into run steps, see Notes blockt at https://www.runatlantis.io/docs/custom-workflows.html#custom-run-command. These variables are partially generated from Infos of the Digger workflow like the Digger/Atlantis project name so they can't just be injected from outside.
A nice use case would be to set the state backend depending on the workflow:
```yaml
projects:
- name: production
  dir: .
  workflow: default
- name: sandbox
  dir: .
  workflow: default

workflows:
  default:
    plan:
      steps:
      - init:
        extra_args: ["-backend-config="key=${BASE_REPO_NAME}/${PROJECT_NAME}.tfstate"]
      - plan:
        extra_args: ["-var-file=configs/${PROJECT_NAME}.tfvars"]
```

This singe workflow allows running multiple environments or deployments in a single directory of terraform code. The states will be separated automatically depending on the digger project name and also different terraform variables can be set per project.

As discussed with @motatoes on Slack, Digger should support at least the same set of Environment variables Atlantis does to be on par with their configuration here. 
As a side note, these injected default variables are in Atlantis only available in `run` steps, not in `init/plan/apply` steps. This is sufficient because a `run` step can set an environment variable like this `TF_CLI_ARGS_plan="-backend-config=\"key=${BASE_REPO_NAME}/${PROJECT_NAME}.tfstate\""` but of course supporting them in `init/plan/apply` steps directly would be even more convenient.

The Atlantis code for these variables can be found here: https://github.com/runatlantis/atlantis/blob/main/server/core/runtime/run_step_runner.go#L39 .
