### ISSUE TITLE
Append output of custom commands as comments (e.g. Infracost)

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#680]
At present, the output of custom run commands (specified in digger.yml) can only be seen in Actions logs, but is not appended to comments

Desired behavior: a config option to append output of the run command into the comment

Example: digger.yml with conftest as custom run command:

```
projects:
- name: prod
  dir: prod
  workflow: my_custom_workflow
workflows:
  my_custom_workflow:
    plan:
      steps:
      - init
      - plan
      - run: "conftest test ./prod.json -p ../policies"
    workflow_configuration:
      on_pull_request_pushed: [digger plan]
      on_pull_request_closed: [digger unlock]
      on_commit_to_default: [digger apply]
```

Proposal: `post_output` option, like this:
```
...
workflows:
  my_custom_workflow:
    plan:
      steps:
      - init
      - plan
      - run:
         command: "conftest test ./prod.json -p ../policies"
         post_output: true
...
```
