### ISSUE TITLE
GH Actions fails on hub CLI invokation

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#685]
When I run digger apply, GH Actions failed at step Checkout Pull Request with error
hub: command not found
I think the errors comes from the code below where the image does not have hub cli command installed
```
jobs:
  digger-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
        if: github.event_name == 'issue_comment'
```
Not sure this is the right way to fix this ?
```
jobs:
  digger-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
        if: github.event_name == 'issue_comment'
```

**Comment by motatoes** [comment]
Not sure about the hub error but note that this is a very outdated way of running digger and we have since moved to composite actions which means that the only step needed is to invocate digger within an action directly, for example:

```
name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: digger run
        uses: diggerhq/digger@v0.1.31
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
