### ISSUE TITLE
Ability to specify the name of "digger.yml" as an argument

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#744]
In some scenarios users want to have more than one workflow file, the common one is that they want to run different github runners for different digger projects.

it would help if there was a way to specify the name of the digger.yml file to use, that way there can be more than one file and different workflows can pick the appropriate one:

```
    steps:
    - name: digger run
      uses: diggerhq/digger@v0.2.0
      with:
        setup-aws: true
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        digger-token: ${{ secrets.DIGGER_TOKEN }}
        digger-organisation: digger
        digger-hostname: https://cloud.digger.dev/
        diggerfile-name: digger_staging.yml
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DIGGER_GITHUB_TOKEN: ${{ secrets.DIGGER_GITHUB_TOKEN }}
```
