### ISSUE TITLE
Dependency scope

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#791]
Only trigger downstream dependent projects if certain outputs change in the upstream (not any change)

Similar to stack dependencies in Spacelift

From user feedback call today (Alexander F)

**Comment by ZIJ** [comment]
Additional feedback from Francois (NT): "all projects are triggered if modules change, even though changes in certain modules aren't affecting certain projects".

**Comment by ZIJ** [comment]
### Idea for using git as a store for dependencies / TFVars

In digger.yml, each project can define `exports` and `imports` lists, like this:

```
projects:
  - name: projA
    dir: ./proj-a
    exports: ["vpcId", "subnetId"]
  - name: projB
    dir: ./proj-b
    imports: ["projA.vpcId", "projA.subnetId"]
```

On every successful apply of a project, all its exports are pushed to git as `outputs.tfvars` file, into either a separate "infra state" repo or a special folder like `.digger`. Folder structure matches digger.yml, like this:

```
.digger
   ├- ProjA
       ├- outputs.tfvars
   ├- ProjB
       ├- outputs.tfvars
```
This ways multi-stage applies for every change can be split in "layers" (effectively levels of the dependency tree):
- Layer 0: A code change triggers an apply of 1 or more porjects. They run in parallel and each produce outputs stored in git
- Layer 1: All projects that consume outputs of layer 0 as inputs
- ...

User may choose to not proceed with Layer 1 after Layer 0 has been applied, or only apply some of the projects by hand and not all.
