### ISSUE TITLE
Caching of terraform dependencies

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#811]
Digger feels slow; Francoi's suggestion is that we might not be using Github cache for terraform dependencies, so it always runs init from scratch

**Comment by JoshuaJackson-jobvite** [comment]
assuming that digger is running terraform relatively standard, having a .terraformrc that has something like:
```
plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"
```
and then you use the cache restore/cache before/after digger runs in the pipeline should just work.

**Comment by JoshuaJackson-jobvite** [comment]
Something like the following should work as an example:

```
name: Digger PR flow

on:
  pull_request:
    branches: ["main"]
    types: [closed, opened, synchronize, reopened]
  issue_comment:
    types: [created]
    if: startsWith(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to merge PRs
      id-token: write # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write # required to validate combined PR status
      packages: read # required to read the packages
      actions: read
    steps:
      # create a temp. token from the github app installed in the org.
      # The app needs to have read access to all private terraform repos  in the org
      # this token is used in the next step to allow cloning terraform module repos
      - uses: actions/cache/restore@v4
        id: restore_cache
        name: restore_cache
        with:
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ hashFiles('**/cache') }}
            ${{ runner.os }}-cache
      - uses: diggerhq/digger@v0.4.2
        with:
          setup-aws: false
          no-backend: true
          disable-locking: true
          digger-hostname: "https://cloud.digger.dev"
          digger-organisation: "XXXX"
          digger-token: ${{ secrets.DIGGER_TOKEN }}
        env:
          GITHUB_OWNER: XXXXX
          TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/cache
      - uses: actions/cache/save@v4
        name: cache-save
        with:
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-${{ hashFiles('**/cache') }}
```
