### ISSUE TITLE
Support project level split of assume role for "state" and "commands"

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#896]
Currently we are supporting project-level assume-role in #886 such as follows:

```
projects:
   - name: dev
      dir: ./dev
      aws_role_to_assume: "arn:/blabla/accid/devaccount"
   - name: prod
      dir: ./prod
      aws_role_to_assume: "arn:/blabla/accid/prodaccount"
```

In case the user wants to split the state account and the account to provision resources this is currently not possible since we assume the same role throughtout. We need to allow a mechanism for separating the state and the cloud resources similar to the one we have in the workflow level:

```
workflows:
  dev:
    envs:
      state:
      - name: AWS_ACCESS_KEY_ID
        value_from: STATE_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        value_from: STATE_SECRET_ACCESS_KEY
```
