### ISSUE TITLE
project-based assume role: Allow OIDC assume role without requiring a default role

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#897]
Currently we are supporting project-level assume-role in https://github.com/diggerhq/digger/pull/886 such as follows:

```
projects:
   - name: dev
      dir: ./dev
      aws_role_to_assume: "arn:/blabla/accid/devaccount"
   - name: prod
      dir: ./prod
      aws_role_to_assume: "arn:/blabla/accid/prodaccount"
```

On the workflow level a default role needs to be specified for the main account role assumption (https://docs.digger.dev/features/project-level-roles). However this should not be needed in the case of OIDC 

We should allow assuming role directly to the account without requiring a role with trust policies (as mentioned here: https://github.com/diggerhq/demo-assume-role-multi-account-aws_diggeryml/blob/main/.github/workflows/diggr_pullrequest_flow.yml#L30)
