### ISSUE TITLE
2 plans are created by digger, on correct one an one without changes

### ISSUE THREAD

**Issue by frank-bee** [diggerhq/digger#904]
With the following config, digger add 2 comments after planning.
One with the correct changes, and one empty plan.
I comment with `digger apply` the changes are not applies (looks like the empty plan is applies)

This is my config
```
name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.6.0
          terraform_wrapper: false

      - name: digger run
        uses: diggerhq/digger@v0.3.0
        with:
          configure-checkout: false
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::123456789:role/github
          aws-region: eu-central-1
          setup-terraform: false
          digger-hostname: 'https://cloud.digger.dev'
          digger-organisation: 'digger'
          digger-token: ${{ secrets.DIGGER_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by frank-bee** [comment]
BTW, this my digger yaml.
To reproduce this I do changes in one of my projects

```
projects:
  - name: ecr
    dir: env/ecr
    terraform_version: v1.6.0
  - name: dev
    dir: env/dev
    terraform_version: v1.6.0
  - name: qa
    dir: env/qa
    terraform_version: v1.6.0
```
