### ISSUE TITLE
Workflow file from main (not PR branch) is used when Digger is triggered via comment directly

### ISSUE THREAD

**Issue by ZIJ** [diggerhq/digger#926]
When Digger is triggered via comment directly and not via backend orchestrator, the version of the workflow file will not taken from the PR branch, but from the main branch instead. This can lead to confusing behaviours (different configuration used for comment vs push)

Ideally the "direct trigger" mode without an orchestrator backend shouldn't be used at all but in reality people use it anyways, so we need to handle it better somehow.

**Comment by ZIJ** [comment]
Tagging @frank-bee - this seems to be the root cause of the issue you're facing

**Comment by frank-bee** [comment]
@ZIJ thanks for your help
What do you mean with "triggering via Github App"? The re is no word about that in the readme you referenced.

**Comment by ZIJ** [comment]
@frank-bee indeed I seem to have introduced confusion, apologies. And docs seem unclear on that, will update

To benefit from the GitHub app you can either use the cloud-based one at https://login.digger.dev/

Or self host the orchestrator:  https://docs.digger.dev/self-host/deploy-binary

**Comment by frank-bee** [comment]
@ZIJ I installed the app, have a token in workflow as well. 
But you mean I have to have these triggers?
```
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
  ```
